### ISSUE TITLE
Question about Error

### ISSUE THREAD

**Issue by tofsjonas** [grudus/Timepicker#4]
Hi there!

Love the Timepicker :)

How would you handle the "Error: There is already one running grudus-timepicker instance!"-error?

Is there an onError or something?

Or maybe a TimePicker.hidePicker()? That would also do the trick

**Comment by cronopio** [comment]
Hi @tofsjonas that is because there is already a TimePicker showed and you are trying to show another one. Need to close the first one in order to display a second TimePicker. Hope this help you. Let me know if need something else.
